# AzureML workspace setup pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: mlWorkspace
  displayName: ML Workspace Name
  type: string
  default: azmlwksb3hgmn
- name: resourceGroup
  displayName: Resource Group Name
  type: string
  default: az-edw-eastus-rg
- name: location
  displayName: Location
  type: string
  default: eastus
- name: serviceConnection
  displayName: ARM Service Connection Name
  type: string
  default: ado-pipeline-sp
- name: model
  displayName: Model Name
  type: string
  default: mnist-model-ado
- name: endpoint
  displayName: Batch Endpoint Name
  type: string
  default: mnist-batch-ado

trigger:
- main
  # branches:
  #     include:
        # - main
  # paths:
  #     include:
  #       - cli/*

pool: mayha-wsl

steps:
  - task: AzureCLI@2
    displayName: Install Azure CLI extension for ML (v2)
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az version
        az extension remove -n azure-cli-ml
        az extension remove -n ml
        az extension add -n ml -y
        az extension update -n ml
        az extension list

  - task: AzureCLI@2
    displayName: Connect to AML Workspace using CLI v2
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az configure --defaults workspace=${{ parameters.mlWorkspace }} group=${{ parameters.resourceGroup }} location=${{ parameters.location }}
  
  - checkout: self
    path: s/

  - task: AzureCLI@2
    displayName: Deploy Model
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az ml model create --name ${{ parameters.model }} --type "custom_model" --path "s/cli/endpoints/batch/mnist-keras/model"

  - task: AzureCLI@2
    displayName: Deploy Batch Endpoint
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az ml batch-endpoint create --name ${{ parameters.endpoint }}

  - task: AzureCLI@2
    displayName: Complete Batch Endpoint Configuration
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az ml batch-deployment create --file "s/cli/endpoints/batch/mnist-keras-deployment.yml" --endpoint-name ${{ parameters.endpoint }} --set-default

  - task: AzureCLI@2
    displayName: Score Batch Endpoint
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        JOB_NAME=$(az ml batch-endpoint invoke --name ${{ parameters.endpoint }} --input https://pipelinedata.blob.core.windows.net/sampledata/mnist --input-type uri_folder --query name -o tsv) 

