# AzureML workspace setup pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
        - main
  paths:
      include:
        - cli/*

pool: mayha-wsl

steps:
  - task: AzureCLI@2
    displayName: Install Azure CLI extension for ML (v2)
    inputs:
      azureSubscription: ado-pipeline-sp
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az version
        az extension remove -n azure-cli-ml
        az extension remove -n ml
        az extension add -n ml -y
        az extension update -n ml
        az extension list

  - task: AzureCLI@2
    displayName: Connect to AML Workspace using CLI v2
    inputs:
      azureSubscription: ado-pipeline-sp
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az configure --defaults workspace=azmlwksb3hgmn group=az-edw-eastus-rg location=eastus

  - task: AzureCLI@2
    displayName: Deploy Model
    inputs:
      azureSubscription: ado-pipeline-sp
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az ml model create --name mnist-ado --type "custom_model" --path "$(System.DefaultWorkingDirectory)/cli/endpoints/batch/mnist-keras/model"

  - task: AzureCLI@2
    displayName: Deploy Batch Endpoint
    inputs:
      azureSubscription: ado-pipeline-sp
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az ml batch-endpoint create --name mnist-batch-mayha

  - task: AzureCLI@2
    displayName: Complete Batch Endpoint Configuration
    inputs:
      azureSubscription: ado-pipeline-sp
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az ml batch-deployment create --file "$(System.DefaultWorkingDirectory)/cli/endpoints/batch/mnist-keras-deployment.yml" --endpoint-name mnist-batch-mayha --set-default

